[package]
name = "rusty_fit"
version = "0.1.0"
authors = ["Jonathan Rothberg <jrothberg@bluebeam.com>"]

[dependencies]
byteorder = "^0.4.2"
rustc-serialize = "0.3.16"


[dependencies.chrono]
version = "0.2"
features = ["rustc-serialize"]
